### ISSUE TITLE
No 

### ISSUE THREAD

**Issue by FriskKiddo** [scholzj/zoo-entrance#4]
I deploy a kafka cluster via strimzi-kafka-operator demo, and that is the all Secret
![image](https://github.com/scholzj/zoo-entrance/assets/39392355/e4b98b60-d2bb-415f-bbcc-817797e4ced2)
I can not find the my-cluster-entity-operator-certs  which the zoo-entrance used in zoo-entrance deployment
![image](https://github.com/scholzj/zoo-entrance/assets/39392355/ea2af7c9-ce98-4195-a697-3b23a8e57f6a)

how to solve it.

**Comment by scholzj** [comment]
I guess you should use the Deployment YAML from the main branch? Maybe you have some old version and need to update it?
