### ISSUE TITLE
Please publish new latest build to fix vulnerabilities

### ISSUE THREAD

**Issue by ajtran303** [scholzj/zoo-entrance#5]
Hello, I ran a vulnerability scanner on the `zoo-entrance:latest` image and found 15 CVE vulnerabilities.

However, the Dockerfile's base image, `ubi-minimal:latest` has none.

I think the zoo-entrance vulnerabilities will be fixed by publishing a new release of the image.

Thank you.

**Comment by scholzj** [comment]
I triggered a rebuild. Please check if is still works and if it has less CVEs.

**Comment by ajtran303** [comment]
It's good, thank you
